export const GET_MOVIE_DETAILS_REQUEST = "GET_MOVIE_DETAILS_REQUEST";
export const GET_MOVIE_DETAILS_SUCCESS = "GET_MOVIE_DETAILS_SUCCESS";
export const GET_MOVIE_DETAILS_FAIL = "GET_MOVIE_DETAILS_FAIL";
export const GET_MOVIE_DETAILS_RESET = "GET_MOVIE_DETAILS_RESET";
