export const GET_SEARCH_MOVIES_REQUEST = "GET_SEARCH_MOVIES_REQUEST";
export const GET_SEARCH_MOVIES_SUCCESS = "GET_SEARCH_MOVIES_SUCCESS";
export const GET_SEARCH_MOVIES_FAIL = "GET_SEARCH_MOVIES_FAIL";