export const GET_SEARCH_MOVIES_REQUEST = "GET_SEARCH_MOVIES_REQUEST";
export const GET_SEARCH_MOVIES_SUCCESS = "GET_SEARCH_MOVIES_SUCCESS";
export const GET_SEARCH_MOVIES_FAIL = "GET_SEARCH_MOVIES_FAIL";

// export const GET_MOVIE_DETAILS_REQUEST = "GET_MOVIE_DETAILS_REQUEST";
// export const GET_MOVIE_DETAILS_SUCCESS = "GET_MOVIE_DETAILS_SUCCESS";
// export const GET_MOVIE_DETAILS_FAIL = "GET_MOVIE_DETAILS_FAIL";
// export const GET_MOVIE_DETAILS_RESET = "GET_MOVIE_DETAILS_RESET";

// export const GET_MOVIE_TRAILER_REQUEST = "GET_MOVIE_TRAILER_REQUEST";
// export const GET_MOVIE_TRAILER_SUCCESS = "GET_MOVIE_TRAILER_SUCCESS";
// export const GET_MOVIE_TRAILER_FAIL = "GET_MOVIE_TRAILER_FAIL";
