export const GET_WATCHLIST_REQUEST = "GET_WATCHLIST_REQUEST";
export const GET_WATCHLIST_SUCCESS = "GET_WATCHLIST_SUCCESS";
export const GET_WATCHLIST_FAIL = "GET_WATCHLIST_FAIL";

export const ADD_TO_WATCHLIST = "GET_MOVIE_TRAILER_REQUEST";
export const REMOVE_FROM_WATCHLIST = "REMOVE_FROM_WATCHLIST";
export const CLEAR_WATCHLIST = "CLEAR_WATCHLIST";
