export const GET_WATCHLIST_REQUEST = "GET_WATCHLIST_REQUEST";
export const GET_WATCHLIST_SUCCESS = "GET_WATCHLIST_SUCCESS";
export const GET_WATCHLIST_FAIL = "GET_WATCHLIST_FAIL";

export const GET_USER_WATCHLIST_REQUEST = "GET_USER_WATCHLIST_REQUEST";
export const GET_USER_WATCHLIST_SUCCESS = "GET_USER_WATCHLIST_SUCCESS";
export const GET_USER_WATCHLIST_FAIL = "GET_USER_WATCHLIST_FAIL";

export const ADD_MOVIE_TO_WATCHLIST_REQUEST = "ADD_TO_WATCHLIST_REQUEST";
export const ADD_MOVIE_TO_WATCHLIST_SUCCESS = "ADD_TO_WATCHLIST_SUCCESS";
export const ADD_MOVIE_TO_WATCHLIST_FAIL = "ADD_TO_WATCHLIST_FAIL";

export const REMOVE_MOVIE_FROM_WATCHLIST_REQUEST =
	"REMOVE_FROM_WATCHLIST_REQUEST";
export const REMOVE_MOVIE_FROM_WATCHLIST_SUCCESS =
	"REMOVE_FROM_WATCHLIST_SUCCESS";
export const REMOVE_MOVIE_FROM_WATCHLIST_FAIL = "REMOVE_FROM_WATCHLIST_FAIL";

export const CLEAR_WATCHLIST = "CLEAR_WATCHLIST";
